import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// layout 쓰는 이유
// 통일된 UI를 적용하기 위해
// 통일된 로직을 적용하기 위해
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
